name: xdg_icons
description: XDG theme icons for Flutter.
homepage: https://github.com/ubuntu-flutter-community/xdg_icons
repository: https://github.com/ubuntu-flutter-community/xdg_icons
issue_tracker: https://github.com/ubuntu-flutter-community/xdg_icons/issues
version: 0.0.1

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  collection: ^1.16.0
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.0
  path: ^1.8.0
  plugin_platform_interface: ^2.1.2

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      linux:
        pluginClass: XdgIconsPlugin
