name: gtk_icon_theme
description: GtkIconTheme FFI bindings
homepage: https://github.com/ubuntu-flutter-community/xdg_icons
repository: https://github.com/ubuntu-flutter-community/xdg_icons
issue_tracker: https://github.com/ubuntu-flutter-community/xdg_icons/issues
version: 0.0.1

environment:
  sdk: '>=2.17.0 <3.0.0'

platforms:
  linux:

dependencies:
  ffi: ^2.0.1
  path: ^1.8.0

dev_dependencies:
  ffigen: ^6.0.1
  lints: ^2.0.0
  test: ^1.16.0

ffigen:
  name: LibGtk
  description: "GtkIconTheme FFI bindings"
  output: "lib/src/gtk.g.dart"
  headers:
    entry-points:
      - "/usr/include/gtk-3.0/gtk/gtk.h"
  compiler-opts:
    - -I/usr/include/atk-1.0
    - -I/usr/include/cairo
    - -I/usr/include/gdk-pixbuf-2.0
    - -I/usr/include/glib-2.0
    - -I/usr/include/gtk-3.0
    - -I/usr/include/harfbuzz
    - -I/usr/include/pango-1.0
    - -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
  globals:
    exclude:
      - ".*"
  functions:
    include:
      - "gtk_icon_.*"
      - "g_free"
      - "g_list_free"
      - "g_object_ref"
      - "g_object_unref"
      - "g_strfreev"
      - "g_resources_lookup_data"
      - "g_bytes_get_data"
      - "g_bytes_unref"
  macros:
    exclude:
      - ".*"
  enums:
    exclude:
      - ".*"
  unnamed-enums:
    exclude:
      - ".*"
  structs:
    include:
      - "GtkIconTheme"
  unions:
    exclude:
      - ".*"
  llvm-path:
    - "/usr/lib/llvm-13"
